

import type { Metadata } from "next";
import { Jura  } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";


const juraSans = Jura({
  variable: "--font-jura-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Medicaflow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Suspense>
      <body
        className={`${juraSans.variable} antialiased`}
      >
        {children}
      </body>
      </Suspense>
    </html>
  );
}
